import sys
"""
Django settings for LoggingProject project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
# from dotenv import load_dotenv


# load_dotenv(override=True)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# settings.py
AUTH_USER_MODEL = 'LogApp.Users'  # replace 'yourapp' with the actual app name


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4#l0xv@7u3(!k9h5v9ftl#m6d^ohsqss#)bb^swr#et=r=au0%'
# SECRET_KEY = os.environ.get("SECRET_KEY")

# # SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = bool(os.environ.get("DEBUG", default=0))

ALLOWED_HOSTS = []
# ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS","127.0.0.1").split(",")




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'LogApp',
    'tailwind',
    'theme',
    'django_browser_reload'
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'LogAppSDP@gmail.com'
EMAIL_HOST_PASSWORD = 'hagy fani crci vgjk'  # App password, NOT your Gmail login password


TAILWIND_APP_NAME = 'theme'

# NPM_BIN_PATH=r"C:\Program Files\nodejs\npm.cmd"
NPM_BIN_PATH = '/usr/local/bin/npm' 
# NPM_BIN_PATH = "C:\\Program Files\\nodejs\\npm.cmd" # Eddy



INTERNAL_IPS = [
    "127.0.0.1",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = 'LoggingProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LoggingProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


# MANUAL db setup
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         # 'NAME': 'swift_exam',
#         # 'USER': 'root',
#         # 'PASSWORD': 'password', # Change password to your password
#         # 'HOST': '127.0.0.1',
#         # 'PORT': '3306',

#         'NAME': 'swiftexam',
#         'USER': 'TA',
#         'PASSWORD': 'SwiftExam_pass1',
#         'HOST': '127.0.0.1',
#         'PORT': '3307',

#         'CONN_MAX_AGE': None,
#         'OPTIONS': {
#             'charset': 'utf8mb4',
#         },
#     }
# }

# autossh db setup from claude
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DATABASE_NAME', 'swiftexam'),
        'USER': os.environ.get('DATABASE_USER', 'TA'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD', 'SwiftExam_pass1'),
        # Use localhost since we're tunneling
        'HOST': os.environ.get('DATABASE_HOST', 'localhost'),
        'PORT': os.environ.get('DATABASE_PORT', '3307'),
        'CONN_MAX_AGE': None,
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}

import sys
from django.conf import settings

if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',  # Use in-memory database for tests
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
