# Generated by Django 5.1.6 on 2025-04-25 23:30

import LogApp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courseid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('sectionid', models.CharField(default='A1', max_length=50)),
                ('semester', models.CharField(default='Fall', max_length=10)),
                ('year', models.IntegerField(default=2025)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('email', models.EmailField(max_length=100)),
                ('UID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=70)),
                ('lname', models.CharField(max_length=70)),
                ('cardnum', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('professor', 'Professor'), ('TA', 'TA')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('examid', models.AutoField(primary_key=True, serialize=False)),
                ('sectionid', models.CharField(max_length=10)),
                ('examName', models.CharField(max_length=100)),
                ('examStart', models.DateTimeField()),
                ('examEnd', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogApp.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Checkins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField(blank=True, null=True)),
                ('isLate', models.BooleanField(default=False)),
                ('examid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogApp.exams')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogApp.students')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='tas',
            field=models.ManyToManyField(blank=True, related_name='ta_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='user',
            field=models.ForeignKey(default=LogApp.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentCourses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section_id', models.CharField(max_length=10)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogApp.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogApp.students')),
            ],
            options={
                'unique_together': {('student', 'course', 'section_id')},
            },
        ),
        migrations.CreateModel(
            name='TACourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LogApp.courses')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL)),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ta', 'course')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='courses',
            unique_together={('name', 'courseid', 'sectionid', 'semester', 'year')},
        ),
    ]
